# Generated by Django 3.0.4 on 2020-04-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='ImageForm',
        ),
    ]
